config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :players, only: %i[new create show]
  resources :achivments
  resources :games
  resources :player_statistics, only: %i[new create show]

  root to: 'teams#index'

  get '/top', to: 'player_statistics#show_top'
end

app/models/achivment.rb
class Achivment < ApplicationRecord
  has_many :player_statistics

  # def top_players_by_stat(team, achivment, limit=5)
  #   Player.joins(:player_statistics).where(player_statistics: {achivment: achivment, team: team}).group("players.id").order("count(*) desc").limit(limit)
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
  has_many :player_statistics

  accepts_nested_attributes_for :team, reject_if: :all_blank
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :achivments
  has_many :player_statistics
  belongs_to :team

  accepts_nested_attributes_for :team, reject_if: :all_blank

  def player_achieved_in_last_5_games?(player, team, achivment)
    last_5_games = team.games.order(created_at: :desc).first(5)
    player_statistics = PlayerStatistic.where(player: player, 
                                             game: last_5_games, 
                                             achivment: achivment)
    player_statistics.any? 
  end

  def self.top_players_by_achivment(achivment, team = nil)
    if team 
      players = self.joins(:player_statistics).where(team: team, player_statistics: {achivment: achivment}).group('players.id').order('count(*) DESC').limit(5)
    else
      players = self.joins(:player_statistics).where(player_statistics: {achivment: achivment}).group('players.id').order('count(*) DESC').limit(5)
    end
  end 
end

app/models/player_statistic.rb
class PlayerStatistic < ApplicationRecord
  belongs_to :player
  belongs_to :game
  belongs_to :achivment
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_many :games
end

app/controllers/achivments_controller.rb
class AchivmentsController < ApplicationController
  def new
    @achivment = Achivment.new
  end

  def create
    @achivment = Achivment.create!(achivment_params)
    redirect_to root_path if @achivment.save
  end

  private

  def achivment_params
    params.require(:achivment).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.create!(game_params)
    redirect_to root_path if @game.save
  end

  private

  def game_params
    params.require(:game).permit(:name, :team, :team_id)
  end
end

app/controllers/player_statistics_controller.rb
class PlayerStatisticsController < ApplicationController
  def show_top
    if params[:achivment_id].present? && params[:team_id].present?
      @achivment = Achivment.find_by(id: params[:achivment_id])
      @team = Team.find_by(id: params[:team_id])
      @players = Player.top_players_by_achivment(params[:achivment_id], params[:team_id])
    elsif params[:achivment_id].present?
      @achivment = Achivment.find_by(id: params[:achivment_id]) 
      @players = Player.top_players_by_achivment(params[:achivment_id])
    end 
  end

  def new
    @player_statistic = PlayerStatistic.new
  end

  def create
    @player_statistic = PlayerStatistic.create!(playerstatistic_params)
    redirect_to root_path if @player_statistic.save
  end

  private

  def playerstatistic_params
    params.require(:player_statistic).permit(:player_id, :game_id, :achivment_id, :team_id)
  end

  def set_player
    @player = Player.find(params[:id])
  end

  def set_achivment
    @achivment = Achivment.find_by(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[show]
  before_action :set_achivment, only: %i[show]

  def show
    @team = @player.team
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.create!(player_params)
    redirect_to root_path if @player.save
  end

  private

  def player_params
    params.require(:player).permit(:name, :team_id)
  end

  def set_player
    @player = Player.find(params[:id])
  end

  def set_achivment
    @achivment = Achivment.find_by(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
    @players = Player.all
    @achivments = Achivment.all
    @games = Game.all
    @player_statistics = PlayerStatistic.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.create!(team_params)
    redirect_to root_path if @team.save
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/achivments_helper.rb
module AchivmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/player_statistics_helper.rb
module PlayerStatisticsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/achivments/_create.html.erb
<%= form_with model: @achivment, local: true do |f| %>

  <%= f.text_field :name %>
  <label">Name</label>

  <%= f.submit "Create" %>

<% end %>

app/views/achivments/new.html.erb
<%= render 'create' %>

app/views/games/_create.html.erb
<%= form_with model: @game, local: true do |f| %>

  <%= f.text_field :name %>
  <label">Name</label>

  <%= f.collection_select(:team_id, Team.all, :id, :name,
                             {prompt: "Выберите команду для матча"}, class: "form-select", id: "autoSizingSelect") %>

  <%= f.submit "Create" %>

<% end %>

app/views/games/new.html.erb
<%= render 'create' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Match</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/player_statistics/_create.html.erb
<%= form_for @player_statistic do |f| %>
  <%= f.label :player_id %>
  <%= f.collection_select :player_id, Player.all, :id, :name %>
  
  <%= f.label :game_id %>
  <%= f.collection_select :game_id, Game.all, :id, :name %>
  
  <%= f.label :achivment_id %>
  <%= f.collection_select :achivment_id, Achivment.all, :id, :name %>

  <%= f.label :team_id %>
  <%= f.collection_select :team_id, Team.all, :id, :name %>
  
  <%= f.submit "Засчитать статистику" %> 
<% end %>

app/views/player_statistics/new.html.erb
<%= render 'create' %>

app/views/player_statistics/show_top.html.erb
<br>

<%= form_tag '', method: :get do %>
  <%= label_tag :achivment_id, 'Показатель:' %>
  <%= select_tag :achivment_id, options_from_collection_for_select(Achivment.all, :id, :name) %>
  
  <%= label_tag :team_id, 'Команда:' %>
<%= select_tag :team_id, options_for_select([['', nil]] + Team.all.map { |t| [t.name, t.id] }) %>
  
  <%= submit_tag 'Показать' %>
<% end %>

<% if @achivment.present? %>
  <p>Показатель: <%= @achivment.name %></p>
<% end %>

<% if @team.present? %>  
  <p>Команда: <%= @team.name %></p>
<% end %>   

<% if @players %>
  <ul>
    <% @players.each do |player| %>
      <li><%= player.name %> - <%= player.player_statistics.where(achivment_id: @achivment.id).count %> раз(а)</li>
    <% end %> 
  </ul>
<% end %>

app/views/players/_create.html.erb
<%= form_with model: @player, local: true do |f| %>

  <%= f.text_field :name %>
  <label>Имя игрока</label>

  <%= f.collection_select(:team_id, Team.all, :id, :name,
                             {prompt: "Выберите команду игрока"}, class: "form-select", id: "autoSizingSelect") %>

  <%= f.submit "Create" %>

<% end %>

app/views/players/new.html.erb
<%= render 'create' %>

app/views/players/show.html.erb
<h1>Показатели игрока <%= @player.name %></h1>


<% if @player.player_achieved_in_last_5_games?(@player, @team, @achivment) %>
  <p>Игрок выполнил показатель "<%= @achivment.name %>" за последние 5 игр!</p>  
<% else %>
  <p>Игрок не выполнил ни один показатель за последние 5 игр!</p>
<% end %>



app/views/shared/_navbar.html.erb
<a class="link" href="<%= new_team_path %>">Добавить команду</a> | 
<a class="link" href="<%= new_player_path %>">Добавить игрока</a> | 
<a class="link" href="<%= new_achivment_path %>">Добавить показатель</a> | 
<a class="link" href="<%= new_game_path %>">Добавить матч</a> | 
<a class="link" href="<%= new_player_statistic_path %>">Добавить статистику</a> | 
<a class="link" href="<%= top_path %>">Посмотреть статистику ТОП 5 игроков</a>
<br>